# Generated by Django 3.1.2 on 2020-10-09 04:11

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=128)),
                ('heading', models.CharField(max_length=24)),
                ('type', models.CharField(choices=[('green', 'green'), ('red', 'red'), ('yellow', 'yellow'), ('blue', 'blue'), ('purple', 'purple')], max_length=64)),
                ('location', models.CharField(max_length=64)),
                ('dueday', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('email', models.EmailField(max_length=64)),
                ('contact', models.IntegerField()),
                ('company', models.CharField(max_length=64)),
                ('sector', models.CharField(choices=[('space', 'Space'), ('electronics', 'Electronics'), ('augmentations', 'Augmentations'), ('server', 'servers'), ('robotics', 'Robotics')], max_length=24)),
                ('est_value', models.IntegerField()),
                ('deal_status', models.BooleanField(default=False)),
                ('lead_status', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now=True)),
                ('date_closed', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36)),
                ('files', models.FileField(upload_to=api.models.files_directory)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('green', 'green'), ('red', 'red'), ('yellow', 'yellow'), ('blue', 'blue'), ('purple', 'purple')], max_length=64)),
                ('date', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(max_length=128)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Leads_created', models.IntegerField(default=0)),
                ('leads_confirmed', models.IntegerField(default=0)),
                ('leads_dropped', models.IntegerField(default=0)),
                ('deals_created', models.IntegerField(default=0)),
                ('deals_dropped', models.IntegerField(default=0)),
                ('deals_confirmed', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to=api.models.profile_directory)),
                ('name', models.CharField(max_length=64)),
                ('address', models.TextField(max_length=128)),
                ('position', models.CharField(max_length=64)),
                ('contact', models.IntegerField()),
                ('qualification', models.CharField(max_length=128)),
                ('clients', models.ManyToManyField(to='api.Client')),
                ('file', models.ManyToManyField(to='api.Files')),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('performance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.performance')),
                ('personal_notes', models.ManyToManyField(to='api.Notes')),
                ('projects', models.ManyToManyField(to='api.Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=64)),
                ('quantity', models.IntegerField()),
                ('demand', models.IntegerField()),
                ('completed', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profile')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.files')),
            ],
        ),
        migrations.AddField(
            model_name='notes',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profile'),
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people', models.ManyToManyField(to='api.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='files',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profile'),
        ),
        migrations.AddField(
            model_name='client',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profile'),
        ),
        migrations.AddField(
            model_name='client',
            name='file',
            field=models.ManyToManyField(to='api.Files'),
        ),
        migrations.AddField(
            model_name='client',
            name='notes',
            field=models.ManyToManyField(to='api.Notes'),
        ),
        migrations.AddField(
            model_name='client',
            name='orders',
            field=models.ManyToManyField(to='api.Order'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profile'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='members',
            field=models.ManyToManyField(blank=True, to='api.Members'),
        ),
    ]
